-- Alberring Connect: security-first core schema
create extension if not exists pgcrypto;
create schema if not exists private;

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organization_settings (organization_id uuid primary key references public.organizations on delete cascade, timezone text not null default 'Europe/Berlin', onboarding_enabled boolean not null default false, leave_approval_steps smallint not null default 1 check(leave_approval_steps between 1 and 2), mileage_reminder_days smallint[] not null default '{25}', retention jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key default gen_random_uuid(), auth_user_id uuid not null unique references auth.users on delete restrict, organization_id uuid not null references public.organizations on delete restrict, display_name text not null, email text not null, avatar_url text, status text not null default 'invited' check(status in ('invited','active','suspended','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,email));
create index profiles_org_status_idx on public.profiles(organization_id,status);
create table public.employee_profiles (profile_id uuid primary key references public.profiles on delete cascade, organization_id uuid not null references public.organizations on delete restrict, first_name text not null, last_name text not null, employee_number text, work_phone text, job_title text, start_date date, end_date date, birth_date date, weekly_hours numeric(5,2), manager_profile_id uuid references public.profiles, created_at timestamptz not null default now(), unique(organization_id,employee_number));
create table public.teams (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, location_name text, lead_profile_id uuid references public.profiles, active boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,name));
create table public.team_memberships (team_id uuid references public.teams on delete cascade, profile_id uuid references public.profiles on delete cascade, organization_id uuid not null references public.organizations on delete cascade, valid_from date not null default current_date, valid_until date, primary key(team_id,profile_id,valid_from));
create table public.permissions (key text primary key check(key ~ '^[a-z_]+\.[a-z_]+$'), description text not null);
create table public.roles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, system_key text, active boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,name));
create table public.role_permissions (role_id uuid references public.roles on delete cascade, permission_key text references public.permissions on delete cascade, primary key(role_id,permission_key));
create table public.user_roles (profile_id uuid references public.profiles on delete cascade, role_id uuid references public.roles on delete cascade, valid_from timestamptz not null default now(), valid_until timestamptz, assigned_by uuid references public.profiles, primary key(profile_id,role_id,valid_from));

create or replace function private.current_profile_id() returns uuid language sql stable security definer set search_path=public,pg_temp as $$ select id from public.profiles where auth_user_id=auth.uid() and status='active' limit 1 $$;
create or replace function private.current_organization_id() returns uuid language sql stable security definer set search_path=public,pg_temp as $$ select organization_id from public.profiles where auth_user_id=auth.uid() and status='active' limit 1 $$;
create or replace function private.has_permission(permission_key text) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.user_roles ur join public.role_permissions rp on rp.role_id=ur.role_id join public.roles r on r.id=ur.role_id where ur.profile_id=private.current_profile_id() and rp.permission_key=$1 and r.active and ur.valid_from<=now() and (ur.valid_until is null or ur.valid_until>now())) $$;
create or replace function public.my_permissions() returns table(permission_key text) language sql stable security definer set search_path=public,pg_temp as $$ select distinct rp.permission_key from public.user_roles ur join public.role_permissions rp on rp.role_id=ur.role_id join public.roles r on r.id=ur.role_id where ur.profile_id=private.current_profile_id() and r.active and ur.valid_from<=now() and (ur.valid_until is null or ur.valid_until>now()) $$;

create table public.conversations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, type text not null check(type in ('direct','group','team','announcement')), name text, team_id uuid references public.teams, created_by uuid not null references public.profiles, archived_at timestamptz, created_at timestamptz not null default now());
create table public.conversation_members (conversation_id uuid references public.conversations on delete cascade, profile_id uuid references public.profiles on delete cascade, organization_id uuid not null references public.organizations, joined_at timestamptz not null default now(), muted_until timestamptz, primary key(conversation_id,profile_id));
create or replace function private.is_conversation_member(cid uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.conversation_members where conversation_id=cid and profile_id=private.current_profile_id()) $$;
create table public.messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, conversation_id uuid not null references public.conversations on delete cascade, sender_id uuid not null references public.profiles, reply_to_id uuid references public.messages, body text not null check(length(body) between 1 and 10000), edited_at timestamptz, retracted_at timestamptz, created_at timestamptz not null default now());
create index messages_conversation_cursor_idx on public.messages(conversation_id,created_at desc);
create table public.message_reactions (message_id uuid references public.messages on delete cascade, profile_id uuid references public.profiles on delete cascade, emoji text not null check(length(emoji)<=16), created_at timestamptz not null default now(), primary key(message_id,profile_id,emoji));
create table public.message_read_receipts (message_id uuid references public.messages on delete cascade, profile_id uuid references public.profiles on delete cascade, read_at timestamptz not null default now(), primary key(message_id,profile_id));

create table public.news_posts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, title text not null, summary text not null, body text not null, status text not null default 'draft' check(status in ('draft','scheduled','published','archived')), priority text not null default 'normal' check(priority in ('normal','important','critical')), author_id uuid not null references public.profiles, published_at timestamptz, expires_at timestamptz, acknowledgement_required boolean not null default false, created_at timestamptz not null default now());
create table public.news_reads (news_id uuid references public.news_posts on delete cascade, profile_id uuid references public.profiles on delete cascade, opened_at timestamptz not null default now(), acknowledged_at timestamptz, primary key(news_id,profile_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, profile_id uuid not null references public.profiles on delete cascade, type text not null, title text not null, body text not null, target_path text, deduplication_key text, read_at timestamptz, created_at timestamptz not null default now(), unique(profile_id,deduplication_key));
create index notifications_profile_unread_idx on public.notifications(profile_id,created_at desc) where read_at is null;

create table public.shifts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, team_id uuid references public.teams, title text not null, starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'draft' check(status in ('draft','published','changed','cancelled')), created_by uuid references public.profiles, created_at timestamptz not null default now(), check(ends_at>starts_at));
create table public.shift_assignments (shift_id uuid references public.shifts on delete cascade, profile_id uuid references public.profiles, organization_id uuid not null references public.organizations, acknowledged_at timestamptz, primary key(shift_id,profile_id));
create table public.leave_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, profile_id uuid not null references public.profiles, leave_type text not null, starts_on date not null, ends_on date not null, day_fraction numeric(2,1) not null default 1 check(day_fraction in (.5,1)), workdays numeric(5,1) not null, note text, status text not null default 'submitted' check(status in ('submitted','review','approved','rejected','withdrawn','cancelled')), decided_by uuid references public.profiles, decided_at timestamptz, decision_note text, created_at timestamptz not null default now(), check(ends_on>=starts_on));
create table public.sick_leave_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, profile_id uuid not null references public.profiles, starts_on date not null, expected_end_on date, end_unknown boolean not null default false, certificate_status text not null default 'not_required', status text not null default 'reported', created_at timestamptz not null default now());
create table public.sick_leave_document_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, sick_leave_id uuid not null references public.sick_leave_records on delete cascade, storage_path text not null, version integer not null, uploaded_by uuid not null references public.profiles, created_at timestamptz not null default now(), unique(sick_leave_id,version));

create table public.document_folders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, parent_id uuid references public.document_folders, name text not null, created_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, folder_id uuid references public.document_folders, owner_profile_id uuid references public.profiles, title text not null, visibility text not null check(visibility in ('organization','team','personal')), archived_at timestamptz, created_at timestamptz not null default now());
create table public.document_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, document_id uuid not null references public.documents on delete cascade, version integer not null, storage_path text not null, mime_type text not null, size_bytes bigint not null check(size_bytes>0), uploaded_by uuid references public.profiles, created_at timestamptz not null default now(), unique(document_id,version));
create table public.vehicles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, internal_name text not null, license_plate text not null, make text, model text, status text not null default 'active', current_mileage integer not null default 0 check(current_mileage>=0), next_service_on date, created_at timestamptz not null default now(), unique(organization_id,license_plate));
create table public.vehicle_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, vehicle_id uuid references public.vehicles, profile_id uuid references public.profiles, valid_from date not null, valid_until date, primary_assignment boolean not null default true);
create unique index vehicle_primary_active_idx on public.vehicle_assignments(vehicle_id) where primary_assignment and valid_until is null;
create table public.mileage_submissions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, vehicle_id uuid references public.vehicles, profile_id uuid references public.profiles, mileage integer not null check(mileage>=0), read_on date not null, reporting_month date generated always as (date_trunc('month',read_on::timestamp)::date) stored, status text not null default 'submitted', photo_path text, created_at timestamptz not null default now(), unique(vehicle_id,profile_id,reporting_month));
create table public.material_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, requester_id uuid references public.profiles, category text not null, item text not null, quantity numeric(10,2) not null check(quantity>0), unit text not null, priority text not null default 'normal', needed_on date, reason text, status text not null default 'submitted', created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, actor_id uuid references public.profiles, action text not null, entity_type text not null, entity_id uuid, request_id uuid not null default gen_random_uuid(), metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.integration_connections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, provider text not null check(provider in ('manual','careville')), status text not null default 'not_configured', config jsonb not null default '{}', updated_at timestamptz not null default now(), unique(organization_id,provider));

do $$ declare t text; begin foreach t in array array['organizations','organization_settings','profiles','employee_profiles','teams','team_memberships','permissions','roles','role_permissions','user_roles','conversations','conversation_members','messages','message_reactions','message_read_receipts','news_posts','news_reads','notifications','shifts','shift_assignments','leave_requests','sick_leave_records','sick_leave_document_versions','document_folders','documents','document_versions','vehicles','vehicle_assignments','mileage_submissions','material_requests','audit_logs','integration_connections'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy profiles_org_read on public.profiles for select using(organization_id=private.current_organization_id() and status<>'archived');
create policy profiles_self_update on public.profiles for update using(id=private.current_profile_id()) with check(id=private.current_profile_id() and organization_id=private.current_organization_id());
create policy conversations_member_read on public.conversations for select using(organization_id=private.current_organization_id() and private.is_conversation_member(id));
create policy conversation_members_member_read on public.conversation_members for select using(organization_id=private.current_organization_id() and private.is_conversation_member(conversation_id));
create policy messages_member_read on public.messages for select using(organization_id=private.current_organization_id() and private.is_conversation_member(conversation_id));
create policy messages_member_insert on public.messages for insert with check(organization_id=private.current_organization_id() and sender_id=private.current_profile_id() and private.is_conversation_member(conversation_id));
create policy notifications_own on public.notifications for select using(profile_id=private.current_profile_id());
create policy notifications_own_update on public.notifications for update using(profile_id=private.current_profile_id()) with check(profile_id=private.current_profile_id());
create policy shifts_own_read on public.shifts for select using(organization_id=private.current_organization_id() and (private.has_permission('schedule.view_team') or exists(select 1 from public.shift_assignments a where a.shift_id=id and a.profile_id=private.current_profile_id())));
create policy leave_own_read on public.leave_requests for select using(organization_id=private.current_organization_id() and (profile_id=private.current_profile_id() or private.has_permission('leave.view_team')));
create policy leave_own_insert on public.leave_requests for insert with check(organization_id=private.current_organization_id() and profile_id=private.current_profile_id() and private.has_permission('leave.create_own'));
create policy sick_own_or_status on public.sick_leave_records for select using(organization_id=private.current_organization_id() and (profile_id=private.current_profile_id() or private.has_permission('sick_leave.view_status') or private.has_permission('sick_leave.manage')));
create policy sick_docs_hr_only on public.sick_leave_document_versions for select using(organization_id=private.current_organization_id() and (uploaded_by=private.current_profile_id() or private.has_permission('sick_leave.view_certificates')));
create policy documents_scoped_read on public.documents for select using(organization_id=private.current_organization_id() and (visibility='organization' or owner_profile_id=private.current_profile_id() or private.has_permission('documents.manage_employee_files')));
create policy vehicles_scoped_read on public.vehicles for select using(organization_id=private.current_organization_id() and (private.has_permission('fleet.view_all') or exists(select 1 from public.vehicle_assignments va where va.vehicle_id=id and va.profile_id=private.current_profile_id() and (va.valid_until is null or va.valid_until>=current_date))));
create policy mileage_own_insert on public.mileage_submissions for insert with check(organization_id=private.current_organization_id() and profile_id=private.current_profile_id() and private.has_permission('mileage.submit_own'));
create policy materials_own_read on public.material_requests for select using(organization_id=private.current_organization_id() and (requester_id=private.current_profile_id() or private.has_permission('materials.manage')));
create policy audit_authorized_read on public.audit_logs for select using(organization_id=private.current_organization_id() and private.has_permission('audit.view'));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('message-attachments','message-attachments',false,10485760,array['image/jpeg','image/png','application/pdf']),
('documents','documents',false,20971520,array['image/jpeg','image/png','application/pdf']),
('sick-certificates','sick-certificates',false,10485760,array['image/jpeg','image/png','application/pdf']),
('vehicle-files','vehicle-files',false,10485760,array['image/jpeg','image/png','application/pdf']),
('avatars','avatars',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy storage_org_boundary on storage.objects for select using(bucket_id in ('message-attachments','documents','vehicle-files','avatars') and (storage.foldername(name))[1]=private.current_organization_id()::text);
create policy certificate_hr_read on storage.objects for select using(bucket_id='sick-certificates' and (storage.foldername(name))[1]=private.current_organization_id()::text and private.has_permission('sick_leave.view_certificates'));
revoke all on function public.my_permissions() from public; grant execute on function public.my_permissions() to authenticated;
